### ISSUE TITLE
Full source code

### ISSUE THREAD

**Issue by kostja93** [PhilThomas/crochety#1]
Hey, my sister showed me an Instagram Reel with this website. I'm kind of curious how this is done. Also I would like to add some suggestions for my sisters specific needs.
Would you mind you share the whole source code?

**Comment by PhilThomas** [comment]
It's a single page app that runs entirely in the browser (no back end).  It is written in typescript using react.

It uses an html `canvas` to access the pixels in the image (look at the MDN site for canvas docs).  It run length encodes each row into a list of runs of pixels with the same color.  Each row's run list is gathered into list of run lists for the whole image.  A react component then iterates the list of lists and spits out a table.  The component keeps track of the currently selected run, and uses a global key down event handler to look for arrow key presses that update the position.

There is some css to make it look OK when printed to pdf, but I haven't kept it up to date after adding new UI elements (which you won't want in a pdf).

I have a new version which I have not yet deployed (because I removed the file input) that allows you to set the corner of the image you want to start crocheting from.

It's all pretty simple, but I'm not ready to release the source just yet, since I want to refactoring it a bit to make it easier to add the new features.

I'm also trying to add image scaling and reduced palette generation using k-means clustering, and I want to use local storage to save preferences (and scaling settings and palettes, etc).  It's a weekend project, so stuff gets done bit by bit.
